default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: liga_mesao_development

test:
  <<: *default
  database: liga_mesao_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB") { "liga_mesao_production" } %>
    username: <%= ENV.fetch("POSTGRES_USER") { "liga_mesao" } %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  cache:
    <<: *primary_production
    database: liga_mesao_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: liga_mesao_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: liga_mesao_production_cable
    migrations_paths: db/cable_migrate
