default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: liga_mesao_development

test:
  <<: *default
  database: liga_mesao_test

production:
  primary: &primary_production
    <<: *default
    database: liga_mesao_production
    username: liga_mesao
    password: <%= ENV["LIGA_MESAO_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: liga_mesao_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: liga_mesao_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: liga_mesao_production_cable
    migrations_paths: db/cable_migrate
